export const types = {
 
  SET_TAB_INDEX: "SET_TAB_INDEX",
  SET_GRID_DATA: "SET_GRID_DATA",
  SET_GRID_FETCH_AGAIN_TO_FALSE: "SET_GRID_FETCH_AGAIN_TO_FALSE",
  SAVE_GRID_SORT_MODEL: "SAVE_GRID_SORT_MODEL",
  SAVE_GRID_FILTER_MODEL: "SAVE_GRID_FILTER_MODEL",


};
